name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: ./
        with:
          command: pnpm i
      - name: Lint
        uses: ./
        with:
          command: pnpm run lint
      - name: Test
        uses: ./
        with:
          command: pnpm t
